using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ContentProcessor;

public struct TileSetAtlasData
{
	// these are the fields generated by us, during source content processing.
	public string Name;
	public int PixelWidth;
	public int PixelHeight;
    public int TileSize;
}


[JsonSerializable(typeof(TileSetAtlasData))]
internal partial class TileSetAtlasDataContext : JsonSerializerContext
{
}

public static class TileSetAtlasWriter
{
	static JsonSerializerOptions options = new JsonSerializerOptions
	{
        IncludeFields = true
	};

	static TileSetAtlasDataContext context = new(options);

	public static void Write(TileSetAtlasData data, string outputPath)
	{
        File.WriteAllText(outputPath, JsonSerializer.Serialize(data, typeof(TileSetAtlasData), context));
	}
}