using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
using MoonWorks.Graphics;

namespace RollAndCash.Data;

public struct TileSetAtlasData
{
	// these are the fields generated by us, during source content processing.
	public string Name;
	public int PixelWidth;
	public int PixelHeight;
    public int TileSize;
}


[JsonSerializable(typeof(TileSetAtlasData))]
internal partial class TileSetAtlasDataContext : JsonSerializerContext
{
}

public static class TileSetAtlasReader
{
	static JsonSerializerOptions options = new JsonSerializerOptions
	{
		PropertyNameCaseInsensitive = true,
        IncludeFields = true
	};

	static TileSetAtlasDataContext context = new(options);

	public static void ReadTileSetAtlas(GraphicsDevice graphicsDevice, TileSet tileSet)
	{
        var data = (TileSetAtlasData)JsonSerializer.Deserialize(
            File.ReadAllText(tileSet.JsonFilePath), typeof(TileSetAtlasData), context
        )!;
		tileSet.Load(graphicsDevice, data);
	}
}
