using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
using MoonWorks.Graphics;
using MoonWorks.Storage;

namespace RollAndCash.Data;

/// <summary>
/// These are the fields generated by us, during source content processing.
/// </summary>
public struct TileSetAtlasData
{
	public string Name;
	public int PixelWidth;
	public int PixelHeight;
    public int TileSize;
}


[JsonSerializable(typeof(TileSetAtlasData))]
internal partial class TileSetAtlasDataContext : JsonSerializerContext
{
}

public static class TileSetAtlasReader
{
	static JsonSerializerOptions options = new JsonSerializerOptions
	{
		PropertyNameCaseInsensitive = true,
        IncludeFields = true
	};

	static TileSetAtlasDataContext context = new(options);

	public static bool ReadTileSetAtlas(
		GraphicsDevice graphicsDevice, 
		TileSet tileSet,
		TitleStorage titleStorage)
	{
        var data = (TileSetAtlasData?)TitleStorageExt.DeserializeJson(
			titleStorage,
			tileSet.PartialJsonFilePath,
			typeof(TileSetAtlasData), 
			context
        );
		if (!data.HasValue)
		{
			return false;
		}
		tileSet.ReLoadAtlasData(graphicsDevice, data.Value);
		return true;
	}
}
