namespace RollAndCash.Data;

public readonly record struct LevelID(LevelType ID);

/// <summary>
/// Lists all levels recognized by the game. <br/>
/// DO NOT RENAME any of these members! <br/>
/// 
/// FIXME: Make this enum auto-generated by scanning folder names 
/// in content source processor!
/// 
/// TODO: Also make it generate static accessors for each level,
/// as well as a list of all levels 
/// w/ basic info (ID, player-facing name, description, etc.)
/// </summary>
public enum LevelType
{
    INVALID = default,

    TestLevel,          START = TestLevel,
    

    END,
    COUNT = END - 1
}